#pragma once

#define GAME_VERSION_MAJOR @GAME_VERSION_MAJOR@
#define GAME_VERSION_MINOR @GAME_VERSION_MINOR@
#define GAME_VERSION_PATCH @GAME_VERSION_PATCH@

#define GAME_VERSION_STRING "@GAME_VERSION_MAJOR@.@GAME_VERSION_MINOR@.@GAME_VERSION_PATCH@"