import re

file_path = "script/sdl_scancode/SDL_scancode.h"

with open(file_path, "r", encoding="utf-8") as file:
    lines = file.readlines()

output_content = """// Auto Generated by script/sdl_scancode/script.py
// Original https://github.com/libsdl-org/SDL/blob/72771ac0b41812065acda4b5c782000293d77ef5/include/SDL3/SDL_scancode.h
#pragma once

namespace KNOT {

enum class ScanCode : unsigned int {
"""

pattern = re.compile(r"SDL_SCANCODE_(\w+)\s*=\s*(\d+)")

for line in lines:
    match = pattern.search(line)
    if match:
        key_name = match.group(1)
        key_value = match.group(2)

        if key_name.isdigit():
            output_content += f"    NUM_{key_name} = {key_value},\n"
        else:
            output_content += f"    {key_name} = {key_value},\n"

output_content += """};

} // namespace KNOT
"""

with open("script/sdl_scancode/keycode.h", "w", encoding="utf-8") as file:
    file.write(output_content)

print("GENEND")