// This is AABB code generated by AI, and it seems to work quite well. It's under CC0, so feel free to use it however you like.

struct AABB {
    glm::vec3 min{ std::numeric_limits<float>::max() };
    glm::vec3 max{ -std::numeric_limits<float>::max() };

    void expand(const glm::vec3& p) {
        min = glm::min(min, p);
        max = glm::max(max, p);
    }

    bool isValid() const {
        return min.x <= max.x && min.y <= max.y && min.z <= max.z;
    }
};

AABB computeWorldAABB(const knot::Object& obj) {
    AABB box;
    if (!obj.model) return box;

    glm::mat4 world = obj.getWorldMatrix();

    for (const auto& sub : obj.model->subMeshes) {
        if (!sub.mesh) continue;

        for (const auto& v : sub.mesh->vertices) {
            glm::vec3 worldPos = glm::vec3(world * glm::vec4(v.Position, 1.0f));
            box.expand(worldPos);
        }
    }

    return box;
}

AABB computeLocalAABB(const knot::Object& obj) {
    AABB box;
    if (!obj.model) return box;

    for (const auto& sub : obj.model->subMeshes) {
        if (!sub.mesh) continue;

        for (const auto& v : sub.mesh->vertices) {
            box.expand(v.Position);
        }
    }

    return box;
}

static bool intersectRayAABB(const glm::vec3& rayOrigin, const glm::vec3& rayDir,
                              const AABB& box, float& tHit) {
    float tmin = 0.0f;
    float tmax = std::numeric_limits<float>::max();

    for (int i = 0; i < 3; ++i) {
        float origin = rayOrigin[i];
        float dir = rayDir[i];
        float minB = box.min[i];
        float maxB = box.max[i];

        if (std::abs(dir) < 1e-8f) {
            if (origin < minB || origin > maxB) return false;
        } else {
            float ood = 1.0f / dir;
            float t1 = (minB - origin) * ood;
            float t2 = (maxB - origin) * ood;
            if (t1 > t2) std::swap(t1, t2);

            tmin = std::max(tmin, t1);
            tmax = std::min(tmax, t2);
            if (tmin > tmax) return false;
        }
    }

    if (tmax < 0.0f) return false;

    tHit = tmin >= 0.0f ? tmin : tmax;
    return true;
}

knot::Object* pickObjectByCameraRay(knot::Scene& scene,
                                     const glm::vec3& rayOrigin,
                                     const glm::vec3& rayDir,
                                     float maxDistance = 6.0f) { // 기본 상호작용 거리
    knot::Object* closestObj = nullptr;
    float closestT = maxDistance;

    for (auto& objPtr : scene.getObjectManager().getObjects()) {
        if (!objPtr) continue;

        AABB box = computeWorldAABB(*objPtr);
        if (!box.isValid()) continue;

        float t;
        if (intersectRayAABB(rayOrigin, rayDir, box, t)) {
            if (t < closestT) {
                closestT = t;
                closestObj = objPtr.get();
            }
        }
    }

    return closestObj;
}